DEFAULT_FPS = 30
DEFAULT_NN_INTERVAL_MS = 20
DEFAULT_NOISE_FILTER_THRESHOLD_US = 10000
DEFAULT_SENSOR_WIDTH = 640
DEFAULT_SENSOR_HEIGHT = 480
DEFAULT_REPLAY_FACTOR = 1.0

DEFAULT_INFERENCE_HOST = "127.0.0.1"
DEFAULT_INFERENCE_PORT = 5555
DEFAULT_NETWORK_TIMEOUT_MS = 1000
DEFAULT_BACKEND_READY_TIMEOUT_S = 180.0

ENV_WSL_DISTRO = "EVENTMAMBA_WSL_DISTRO"
ENV_LINUX_PYTHON = "EVENTMAMBA_LINUX_PYTHON"
ENV_BACKEND_READY_TIMEOUT_S = "EVENTMAMBA_BACKEND_READY_TIMEOUT_S"

DEFAULT_WSL_DISTRO = "EventMamba_mini"
DEFAULT_LINUX_PYTHON = "/opt/miniconda3/envs/eventmamba/bin/python"
