DEFAULT_FPS = 30
DEFAULT_NN_INTERVAL_MS = 20
DEFAULT_NOISE_FILTER_THRESHOLD_US = 10000
DEFAULT_REPLAY_FACTOR = 1.0
DEFAULT_SENSOR_WIDTH = 640
DEFAULT_SENSOR_HEIGHT = 480

DEFAULT_INFERENCE_HOST = "127.0.0.1"
DEFAULT_INFERENCE_PORT = 5555
DEFAULT_NETWORK_TIMEOUT_MS = 1000
DEFAULT_BACKEND_READY_TIMEOUT_S = 180.0

ENV_INFERENCE_RUNTIME = "EVENTMAMBA_INFERENCE_RUNTIME"
ENV_WINDOWS_PYTHON = "EVENTMAMBA_WINDOWS_PYTHON"
ENV_WINDOWS_BACKEND_EXECUTABLE = "EVENTMAMBA_WINDOWS_BACKEND_EXECUTABLE"
ENV_CENTER_ONNX_MODEL = "EVENTMAMBA_CENTER_ONNX_MODEL"
ENV_ELLIPSE_ONNX_MODEL = "EVENTMAMBA_ELLIPSE_ONNX_MODEL"
ENV_ELLIPSE_MATRIX = "EVENTMAMBA_ELLIPSE_MATRIX"
ENV_SELECTIVE_SCAN_DLL = "EVENTMAMBA_SELECTIVE_SCAN_DLL"
ENV_WSL_DISTRO = "EVENTMAMBA_WSL_DISTRO"
ENV_LINUX_PYTHON = "EVENTMAMBA_LINUX_PYTHON"
ENV_BACKEND_READY_TIMEOUT_S = "EVENTMAMBA_BACKEND_READY_TIMEOUT_S"

DEFAULT_INFERENCE_RUNTIME = "windows"
DEFAULT_WINDOWS_PYTHON = ".venv-onnx-win/Scripts/python.exe"
DEFAULT_WINDOWS_BACKEND_EXECUTABLE = "backend_runtime/UI_Event_Backend.exe"
DEFAULT_CENTER_ONNX_MODEL = "artifacts/eventmamba_center_native_fps.onnx"
DEFAULT_ELLIPSE_ONNX_MODEL = "artifacts/eventmamba_ellipse_native_fps.onnx"
DEFAULT_ELLIPSE_MATRIX = "artifacts/eventmamba_ellipse_matrix_A.npy"
DEFAULT_SELECTIVE_SCAN_DLL = (
    "native/selective_scan_ort/bin/eventmamba_selective_scan.dll"
)
DEFAULT_WSL_DISTRO = "EventMamba_mini"
DEFAULT_LINUX_PYTHON = "/opt/miniconda3/envs/eventmamba/bin/python"
